- name: Install Docker
  hosts: ansible-client-one 
  tasks:
    - name: install packages 
      ansible.builtin.apt:
        name: 
          - ca.certificates
          - curl
          - gnupg
        state: present
        update_cache: yes

    - name: Add Dockers official GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/debian/gpg 
        state: present
        
    - name: Add docker repository into sources list
      ansible.builtin.apt_repository:
        repo: deb https://download.docker.com/linux/debian bullseye stable
        state: present
       
    - name: update cache
      ansible.builtin.apt:
        update_cache: yes

    - name: install docker packages 
      ansible.builtin.apt:
        name: 
          - docker-ce
          - docker-de-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
          - docker-compose
        state: present
        update_cache: yes
