version: '3'
services:
  frontend:
    image: "{{ client image }}"
    ports:
      - 3000:3003
    networks:
      yolo-ken-network:
        ipv4_address: 172.20.0.4
  backend:
    image: "{{ backend image }}"
    ports:
      - 5000:5000
    environment:
      MONGODB_URI: 'mongodb://Ken:Kasee@172.20.0.2:27017'
      PORT: 5000
    depends_on:
      - mongo
    networks:
      yolo-ken-network:
        ipv4_address: 172.20.0.3    
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: Ken
      MONGO_INITDB_ROOT_PASSWORD: Kasee
    ports:
      - 27017:27017
    networks:
      yolo-ken-network:
        ipv4_address: 172.20.0.2
networks:
  yolo-ken-network:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.1
        